<?xml version="1.0" encoding="utf-8"?><Database Name="Payroll" Class="PayrollDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=JONATHAN-PC\SQLEXPRESS;Initial Catalog=Payroll;Integrated Security=True" SettingsObjectName="Payroll.DataAccess.Properties.Settings" SettingsPropertyName="PayrollConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Employee" Member="Employees">
    <Type Name="Employee">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="EmployeeNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="MiddleName" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Age" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Birthdate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Sex" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="CivilStatus" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="HomePhone" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="MobilePhone" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="PresentHomeAddressId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="DepartmentCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PositionCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TaxStatusCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="HireDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="EmployementTypeCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SSSNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TINNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PagIbigNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PhilHealthNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SalaryRate" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CurrentSalary" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="BankNameCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AccountNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EmployeeStatus" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Employee_EmployeeAddress" Member="EmployeeAddresses" ThisKey="Id" OtherKey="EmployeeId" Type="EmployeeAddress" />
    </Type>
  </Table>
  <Table Name="dbo.EmployeeAddress" Member="EmployeeAddresses">
    <Type Name="EmployeeAddress">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="EmployeeId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="AddressTypeCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="CityMun" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="ProvState" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="CountryCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ZipCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Association Name="Employee_EmployeeAddress" Member="Employee" ThisKey="EmployeeId" OtherKey="Id" Type="Employee" IsForeignKey="true" />
    </Type>
  </Table>
</Database>